Fix compile error for uptime sensor with esp-idf
When compiling with esp-idf, the human readable uptime sensor example yields an error:

bedside-lamp-dev-stock-config.yaml: In lambda function:
bedside-lamp-dev-stock-config.yaml:89:17: error: 'String' was not declared in this scope
bedside-lamp-dev-stock-config.yaml:89:17: note: suggested alternative: 'trunc'

Fixed by switching to `to_string(...)` instead of using `String(...)`.